### ISSUE TITLE
Connections/Ollama API testing - http://host.docker.internal:11434 is failing

### ISSUE THREAD

**Issue by strus38** [substratusai/kubeai#145]
Hi

Environment: **kubeai 0.4.1**

How to fix the default URL http://host.docker.internal:11434 of Ollama within K8S?
Of course this can not work by default, but I cannot find any parameters anywhere (helm) to fix it or even whicch value should be set.
I just added in my Helm deployment:
```
...
- name: ENABLE_OLLAMA_API
    value: "True"
...
```
Thanks for the help.

**Comment by samos123** [comment]
Thanks for trying it out and filing the issue. What's the reason for enabling the Ollama API? We utilize the same OpenAI compatible API so we can re-use it across vLLM and Ollama. Just want to make sure I understand the use case properly before diving into fixing it.

**Comment by strus38** [comment]
I was using the OpenWeb UI interface and in the admin section you have this:
<img width="511" alt="image" src="https://github.com/user-attachments/assets/4258d8b8-652e-4cd3-9337-3eee1e694804">

So, I was kind of curious to see what would happen ... and it failed.

But the main goal was really to use this capability:
<img width="329" alt="image" src="https://github.com/user-attachments/assets/4f221407-c6c8-46e5-9268-1a6c836f784d">

Which can only work with the setting correctly set.

Is it clearer?
Thanks

**Comment by nstogner** [comment]
Hey there @strus38, the Open WebUI project allows for users to integrate directly with a local instance of Ollama. While this works well when you are running Open WebUI on your local machine, this feature does not match very well with how KubeAI manages models. Because KubeAI is intended to operate at scale it spins up model servers (like Ollama or vLLM) as additional Pods across the cluster. I think we probably need to disable that settings page to avoid confusion.

**Comment by strus38** [comment]
Thanks, clear to me, and that would also explain why I also have an error when trying to use a model I have uploaded only through this same web interface as a user in my workspace, agree?

**Comment by nstogner** [comment]
Yes, exactly. I will get a doc written up today that explains how to accomplish what you are trying to do in KubeAI. We still have some rough edges with chat UI integration and appreciate the feedback!

**Comment by nstogner** [comment]
Adding doc in #149
