### ISSUE TITLE
Helm upgrade does not upgrade CRDs

### ISSUE THREAD

**Issue by nstogner** [substratusai/kubeai#213]
Current method of specifying CRDs is ignored when upgrading helm release.

See: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

Possible solution:

* Move CRDs to `./charts/kubeai/templates`
* Move model up a level to be its own chart

Bonus:

* Template a catalog of individual `<model-name>.yaml` files that could be installed with `kubectl apply -f https://...` directly. Probably makes sense to do this with the models chart.

**Comment by samos123** [comment]
I think moving CRDs to templates would be easier for users.

1. Move CRDs to templates/: Relocate your CRD YAML files from the crds/ directory to the templates/ directory.
2. Use Helm Hooks: Add the following annotations to your CRD YAML files to ensure they are applied before other resources:

```
metadata:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
```
