### ISSUE TITLE
Messaging: Scale up based on pending messages

### ISSUE THREAD

**Issue by samos123** [substratusai/kubeai#229]
Update, it just went slowly from 0 to 1 to 4 eventually.

Current behavior:
* kubeai configured to read from pubsub with max handlers at 2500, model targetRequests set to 500
* 5M messages get send
* KubeAI receives 2500 messages
* KubeAI scales from 0 to 1

Expected heavior:
* kubeai scales from 0 to 5 when it knows there are 2500 pending requests

Some other thoughts, maybe we should look at total unacked messages in queue and go to max scale based on that.

This issue is more problematic than I thought because it took about 2 hours to scale from 0 to 8 pods. It does it 1 by 1 and each pod scaling up is slow.

**Comment by nstogner** [comment]
Done
