### ISSUE TITLE
Error when installing kubeai

### ISSUE THREAD

**Issue by flightefore** [substratusai/kubeai#232]
Install kubeai according to the steps prompted by the official website documentation. When proceeding to helm installation, the error message cannot be installed as shown in the figure below. How to solve it?
![error](https://github.com/user-attachments/assets/a023d164-4b3f-4919-a98b-9ccb081a4708)

**Comment by samos123** [comment]
Thanks for sharing the details. I am not able to reproduce this, but some other user was. I plan to put in a fix anyway, but could you share:
* Helm version
* Kubectl version
* K8s distro and version

**Comment by samos123** [comment]
This has been fixed in the latest helm release.

@flightefore can you please run `help repo update` and try again?  I would like to confirm that it's fixed now.

Make sure you use the helm chart version `0.4.2`.
