### ISSUE TITLE
OpenAI Server incompatible with OpenAI API when streaming and requesting usage

### ISSUE THREAD

**Issue by tpfau** [substratusai/kubeai#283]
Hi,

I'm not entirely sure, whether this is an issue in this project, or an upstream project, but I'm encountering an incompatibility between the OpenAI API definition and the responses given by the server spun up by kubeai. 
According to the spec, when specifying `include_usage = true` in `stream_options`the behaviour should be:
```
If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value.
```
However, the responses that I get include the usage in each chunk with increasing token numbers for the completion. 
This breaks the assumption, that usage is null on normal chunks which can otherwise be used to distiguish between "usage" and "content" chunks. 

I'm happy to report this upstream if it is an issue with a tool used by kubeai, but admittedly, I'm not sure where this arises.

**Comment by nstogner** [comment]
Thank you for filing the issue, we will investigate

**Comment by nstogner** [comment]
Can you add some details on what your Model spec looked like? and what version of KubeAI you installed?

**Comment by samos123** [comment]
In addition to what Nick said about Model spec, can you also provide the code you used to send a request and reproduce this behavior? I think I can produce the code based on your description, but don't want to make assumptions and not be able to reproduce.

The most important part of your model spec would be what engine you used, did you use vLLM or Ollama?

**Comment by tpfau** [comment]
As for the kubeai version:
I installed it according to the instructions a few days ago. Would need to check the exact version (and will fill it in tomorrow)
The engine is vllm. (Will provide the exact spec also tomorrow).

**Comment by tpfau** [comment]
The config for the model is:
```
catalog:
  llama-3.1-8b-instruct-fp8-l4:
    enabled: true
    minReplicas: 0
```
Kubeai:
```
NAME         	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART       	APP VERSION
kubeai       	kubeai   	2       	2024-10-23 14:12:37.395280329 +0300 EEST	deployed	kubeai-0.7.0	v0.9.0     
kubeai-models	kubeai   	4       	2024-10-23 14:13:34.411058633 +0300 EEST	deployed	models-0.7.0	1.16.0

```

**Comment by samos123** [comment]
I think you're hitting this open bug  in vLLM: https://github.com/vllm-project/vllm/issues/7262

Can you confirm that you're seeing the same behavior?

**Comment by tpfau** [comment]
It's a crucial feature if you want to use a usage logging gateway for opensource models and don't want to start hacking in the server code / do prompt tokenization externally (which can be quite annoying for chat completions). Determining the chat template used by a model is really annoying and would require essentially replicating the whole prompt processing in the gateway, which is a complete waste of resources, and there is no other way to just get the correct prompt tokens from the input.
