### ISSUE TITLE
how to access model files by pvc?

### ISSUE THREAD

**Issue by qiankunli** [substratusai/kubeai#303]
Assuming all model files are stored on OSS/bucket, PVs are provided through StorageClass（related with oss）, and each model pod is associated with a PVC. Within the pod, VLLM can access model files by accessing a mounted directory( like`/data/models`).

How should the above mode be configured?

**Comment by nstogner** [comment]
Hey there, thanks for submitting an issue!

Currently KubeAI supports loading models from non volume locations (i.e. huggingface hub). We do support caching models to volumes (See [caching docs](https://www.kubeai.org/concepts/storage-caching/#b-model-on-shared-filesystem-read-write-many)). With the current caching implementation, KubeAI manages the PVC itself and always downloads the model from elsewhere (i.e. huggingface hub).

It sounds like you want to define a PVC / PV as the source of the model (not just a caching location)? If so, can you elaborate a little more on your system design?

**Comment by qiankunli** [comment]
The following diagram is my understanding of KubeAI (there may be errors).

![whiteboard_exported_image (4)](https://github.com/user-attachments/assets/9e8d8b33-e5a9-4e29-87d0-7ae577fecff4)

China cannot directly access Hugging Face, so we usually download the model file with proxy and then upload it to a bucket on OSS. There is a corresponding StorageClass for OSS to provide PV and PVC for the bucket, allowing the pod to access the model files through the PVC, as if the model files were in a directory within the pod.

![whiteboard_exported_image (4)](https://github.com/user-attachments/assets/0b84cc46-aae2-443e-9ea4-2c2172a9dab2)

**Comment by samos123** [comment]
@qiankunli curious if this would help with your use case as well? https://github.com/substratusai/kubeai/issues/311

**Comment by nstogner** [comment]
Adding direct support for `oss://` urls here: #304

**Comment by nstogner** [comment]
OSS is now supported: https://www.kubeai.org/how-to/authenticate-to-model-repos/#alibaba-object-storage-service

**Comment by samos123** [comment]
@qiankunli  Storing models on a PVC is now supported with vLLM engine. Please update your helm chart to v0.10.0 or later to try it out.
