### ISSUE TITLE
Handle model backend deployment deletions

### ISSUE THREAD

**Issue by alpe** [substratusai/kubeai#42]
When a deployment for a model backend is deleted from the k8s cluster all pending requests should be aborted and new requests rejected with 404.

**Comment by nstogner** [comment]
Should we mark this as resolved after merging #44?

**Comment by alpe** [comment]
There is also the case where a model was removed from an annotation. This is not handled, yet

**Comment by samos123** [comment]
archiving old issues that likely aren't relevant after KubeAI refactor
