### ISSUE TITLE
Configure a default timeout of 30 minutes

### ISSUE THREAD

**Issue by samos123** [substratusai/kubeai#58]
Any request that's pending for more than 30 minutes should return a 408 HTTP timout error

This timeout should be configurable. A value of 0 would disable it such that there is no timeout.

**Comment by nstogner** [comment]
I am not up to speed on the correct implementation off the cuff so I skimmed this article and it looks pretty informative: https://ieftimov.com/posts/make-resilient-golang-net-http-servers-using-timeouts-deadlines-context-cancellation/
