### ISSUE TITLE
Service name shouldn't have to match deployment name

### ISSUE THREAD

**Issue by samos123** [substratusai/kubeai#59]
Currently it's hardcoded that a service name should match deployment name https://github.com/substratusai/lingo/blob/8c381444dfd2a957964f471ae9cb528cb5b666fd/pkg/endpoints/manager.go#L93

See relevant code in endpoints/manager.go:
```
	const serviceNameLabel = "kubernetes.io/service-name"
	serviceName, ok := slice.GetLabels()[serviceNameLabel]
	if !ok {
		log.Printf("no service label on endpointslice: %v", req.Name)
		return ctrl.Result{}, nil
	}

	if priorLen != len(ips) {
		// TODO: Currently Service name needs to match Deployment name, however
		// this shouldn't be the case. We should be able to reference deployment
		// replicas by something else.
		r.EndpointSizeCallback(serviceName, len(ips))
	}
```

We should try and get rid of this hardcoded assumption that service name is same as deployment name.

Some ideas:
* Utilize a pod watcher and get IP addresses directly from the pod resource, this would allow us to get rid of the requirement of defining any Service.
* Have Lingo work at the K8s Service level instead of having annotations at the Deployment resource

**Comment by samos123** [comment]
@alpe what are your thoughts on this? I personally prefer the idea of having a Pod reconciler.

**Comment by alpe** [comment]
🤔 The pods do not contain the `lingo.substratus.ai/models` annotation but the deployment does, currently.
When watching the pods, you would have to do additional queries to follow the path to the model:`pod.ownerReferences ->replicaSet.ownerReference->deployment.annotations`. 
Moving the model annotation to the pods spec can be a short cut. But as pods are scaled up and down, we would still have to watch the deployments as pods may be scaled down to 0 and not be found on lingo bootstrap.

With the annotation on the service, we don't have the state problem as the service does either exist or not. But we have a hard time to fetch the replica set to scale up/ down. There is no direct path. So either we rely on the convention or duplicate the model data which seem error prune.

The autoscaler does also use the endpoint manager to fetch all lingo instances to collect metrics. Any solution needs to take care of this as well.

**Comment by nstogner** [comment]
Note: Drawback to watching Pods is that it makes Lingo less scalable / more resource intensive at larger scales. Pods are noisy objects that can generate a lot of api-server traffic for the controller to watch and cache. EndpointSlices change much less.

```bash
k get endpointslices -w
NAME             ADDRESSTYPE   PORTS     ENDPOINTS    AGE
my-nginx-njzlr   IPv4          <unset>   <unset>      14m
my-nginx-njzlr   IPv4          80        10.244.0.10   15m
my-nginx-njzlr   IPv4          80        10.244.0.10   15m
my-nginx-njzlr   IPv4          <unset>   <unset>       15m
```

```bash
k get pods -w
NAME                        READY   STATUS    RESTARTS   AGE
my-nginx-56b674f96b-569w6   0/2     Pending   0          0s
my-nginx-56b674f96b-569w6   0/2     Pending   0          0s
my-nginx-56b674f96b-569w6   0/2     ContainerCreating   0          0s
my-nginx-56b674f96b-569w6   2/2     Running             0          3s
my-nginx-56b674f96b-569w6   2/2     Terminating         0          18s
my-nginx-56b674f96b-569w6   0/2     Terminating         0          48s
my-nginx-56b674f96b-569w6   0/2     Terminating         0          49s
my-nginx-56b674f96b-569w6   0/2     Terminating         0          49s
my-nginx-56b674f96b-569w6   0/2     Terminating         0          49s
```

**Comment by nstogner** [comment]
My preference to remove the need to have a matching Service name would be to utilize a lingo-model label on the Service object (which will get propagated to the labels on the EndpointSlice object that Lingo already watches).

**Comment by samos123** [comment]
So we would have annotations on the service and on the deployments? Can you share some more of your idea on how it would work with having annotations on Service? E.g. would min and max scale still be on the deployment?

I think I rather use the target ref object on the endpoint in that case to map it to a deployment name. Let me cook up a quick PR that I almost got working previously. That way we don't have to move annotations to the Service object or to the pod object.

**Comment by samos123** [comment]
Another idea could be a new CRD?
```
LingoService:
  models: ["mixtral"]
  labelSelector:
  conccurency
  minScale
  maxScale
  conccurency: 
  # Optional, if not specified a service will be automatically created
  service: nameOfK8sService
```

I am leaning towards a CRD, this CRD could be used to create the K8s Service for the user?

**Comment by nstogner** [comment]
Introducing CRDs creates practical complications for installing Lingo:

* The installer must have cluster admin privileges.
* There can only be one canonical install of the CRD in the entire cluster - Lingo must be managed centrally in a multi-tenant cluster.

Today Lingo is wholly Namespaced and that makes it feasible for any user to adopt it into their Namespace in a multi-tenant cluster.

**Comment by alpe** [comment]
I can see that CRDs can add a lot of complexity. @nstogner can you give a more concrete example for the label idea? Currently the model annotation can contain multiple models on the deployment. That would be challenging with the label approach as the list would be used as single string value within k8s.
When labels are not used for search then an annotation on the service can be a better fit, too.

The main problem that I had when working on the spike is that there is no direct path from service to deployment. So why don't we just add an annotation for this on the service instead?
