### ISSUE TITLE
Refactor logging to use library

### ISSUE THREAD

**Issue by samos123** [substratusai/kubeai#79]
@nstogner suggested to use: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/log which uses logr.

**Comment by alpe** [comment]
Sounds good for me. What do you suggest as underlying logger? I like zap.

**Comment by nstogner** [comment]
I agree with zap. Zap is actually the underlying logger that is typically used in kubernetes controllers. Here is a good example of logger setup for a controller: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
